language: elixir
cache:
  directories:
  - $HOME/.plt
elixir:
  - 1.3.1
  - 1.2.6
otp_release:
  - 19.0
  - 18.3
env:
  - MIX_ENV=test
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 19.0
before_script:
  - mkdir -p $HOME/.plt
  - mix dialyzer.plt
script:
  - mix dialyzer --halt-exit-status
  - mix coveralls.travis
