language: elixir
cache:
  directories:
  - $HOME/.plt
elixir:
  - 1.8.1
  - 1.7.4
  - 1.6.6
  - 1.5.3
  - 1.4.5
  - 1.3.4
  - 1.2.6
otp_release:
  - 22.0
  - 21.3.8
  - 20.3
  - 19.3
  - 18.3
env:
  - MIX_ENV=test
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 19.0
before_script:
  - mkdir -p $HOME/.plt
  - mix dialyzer.plt
script:
  - mix dialyzer --halt-exit-status
  - mix credo
  - mix coveralls.travis
