language: elixir
cache:
  directories:
  - $HOME/.plt
elixir:
  - 1.8.1
  - 1.7.4
  - 1.6.6
otp_release:
  - 22.0
  - 21.3.8
  - 20.3
  - 19.3
env:
  - MIX_ENV=test
matrix:
  exclude:
    - elixir: 1.8.1
      otp_release: 19.3
    - elixir: 1.8.1
      otp_release: 18.3
    - elixir: 1.2.6
      otp_release: 19.3
before_script:
  - mkdir -p $HOME/.plt
script:
  - mix format --check-formatted mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}"
  - mix credo
  - mix coveralls.travis
